### ISSUE TITLE
Improve video quality

### ISSUE THREAD

**Issue by sabman** [sabman/company-site-spatial-labs#1]
## DoD

The following are deployed and live:

- [ ] Light mode video ([original source](https://www.pexels.com/video/drone-footage-a-river-in-the-metropolitan-city-4787395/)) the annotation are blurry. See if we can make them sharper. Video is available at: 

https://github.com/sabman/company-site-spatial-labs/assets/1907/42176c0e-7cc2-41d6-a340-f1e23ea973dc

- [ ] Dark mode video ([source](https://www.pexels.com/video/hyperlapse-of-a-coastal-city-at-night-12565075/)) add annotations and pre for website. Video is available at: 

https://github.com/sabman/company-site-spatial-labs/assets/1907/7e407d65-2dad-4993-b3c3-5eb6510ab94f

**Comment by Anumfaisal** [comment]
81401a9
