### ISSUE TITLE
Review and publish Nabeel's blog post

### ISSUE THREAD

**Issue by sabman** [sabman/company-site-spatial-labs#4]
- [ ] https://github.com/sabman/company-site-spatial-labs/blob/main/src/content/post/handling-outliers.md 
- [ ] https://github.com/sabman/company-site-spatial-labs/blob/main/src/content/post/data-preprocessing.md

**Comment by sabman** [comment]
@nabeelraza-7 have you provided all the images for this?

**Comment by nabeelraza-7** [comment]
> @nabeelraza-7 have you provided all the images for this?

You mean the graphs that are being used here? Yes, they are in `public>assets>handling outliers`.

**Comment by nabeelraza-7** [comment]
Add this third part as well: https://github.com/sabman/company-site-spatial-labs/blob/main/src/content/post/object-detection.md
